replicaCount: 2
image:
  repository: <your_ecr_repo_url>
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

resources: {}

# === app/server.js ===
const express = require('express');
const app = express();
const port = 3000;

app.get('/', (req, res) => {
  res.send('Hello from production-grade DevOps CI/CD pipeline!');
});

app.listen(port, () => {
  console.log(`App running on http://localhost:${port}`);
});
